# Generated by Django 3.2.6 on 2022-09-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collectors',
            fields=[
                ('collectorid', models.AutoField(db_column='collectorID', primary_key=True, serialize=False)),
                ('room_number', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'collectors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('dataid', models.AutoField(db_column='dataID', primary_key=True, serialize=False)),
                ('humidity', models.IntegerField(blank=True, null=True)),
                ('temp', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'data',
                'managed': False,
            },
        ),
    ]
